# Generated by Django 5.2.7 on 2026-02-21 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0009_weblog_pub_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='receipt',
            field=models.ImageField(blank=True, null=True, upload_to='receipts/'),
        ),
    ]
